### ISSUE TITLE
Parse problem A first

### ISSUE THREAD

**Issue by ouuan** [fjzzq2002/CFBooster#1]
It may take a long time to get all statements, thus the purpose — solve problems faster can't be achieved. Parse problem A / A & B first may solve this problem.

**Comment by fjzzq2002** [comment]
On my side, the load is relatively fast (like 3~5s?) so you can just read the problem in the meantime. If the load is really slow, probably you can connect through proxy (you can configure that in the code) or use a mirror. Is that really super slow for you?

**Comment by ouuan** [comment]
I changed `http_proxy` and `https_proxy` but forgot to delete `proxyDict=None` T_T

**Comment by ouuan** [comment]
Now it's fast enough.
